openapi: 3.0.0
info:
  description: Digital Peace Talks OpenAPI 3.0 server.
  title: DPT-server
  version: 0.1.0
servers:
  -
    description: Development server
    url: http://127.0.0.1:8080/api/v0/
  -
    description: Staging server
    url: https://staging.digitalpeacetalks.org/api/v0
  -
    description: Production server
    url: https://digitalpeacetalks.org/api/v0
paths:
  /singin/:
    post:
      description: Sign in user
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/PublicKey"
      responses:
        200:
          description: OK
        400:
          description: Bad Request
  /singup/:
    post:
      description: Sign up user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublicKey"
      responses:
        200:
          description: OK
        400:
          description: Bad Request
components:
  schemas:
    Message:
      description: Signed message from user to channel.
      type: object
      allOf:
        - $ref: "#/components/schemas/PublicKey"
        - $ref: "#/components/schemas/Signature"
      properties:        
        channel:
          description: Base64Url encoded channel identifier
          type: string
          pattern: ^[A-Za-z0-9_-]{43}$
        timestamp:
          description: ISO 8601 UTC timestamp (does not accept leap seconds)
          type: string
          pattern: ^20[0-9]{2}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|30|31)T([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])Z$
      required:
        - channel
        - timestamp
        - publicKey
        - signature
    PublicKey:
      description: Ed25119 256-bit public key
      type: object
      properties:
        publicKey:
          description: Base64Url encoded public key
          type: string
          pattern: ^[A-Za-z0-9_-]{43}$
      required:
        - publicKey
    Signature:
      description: Ed25119 256-bit message signature
      type: object
      properties:
        signature:
          description: Base64Url encoded signature
          type: string
          pattern: ^[A-Za-z0-9_-]{43}$
      required:
        - signature